name: Native Image

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build-dev:
    name: 'Build Native Image ${{ matrix.platform }}'
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        include:
          - os: 'ubuntu-latest'
            platform: 'linux-amd64'
            executable-suffix: ''
          - os: 'windows-latest'
            platform: 'win-amd64'
            executable-suffix: '.exe'
    runs-on: ${{matrix.os}}
    permissions:
      contents: write
    steps:
      - name: linux packages
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt install libasound2-dev libavcodec-dev libavformat-dev libavutil-dev libgl-dev libgtk-3-dev libpango1.0-dev libxtst-dev

      - name: Checkout the repository
        uses: actions/checkout@v4

      - uses: graalvm/setup-graalvm@v1
        with:
          distribution: 'liberica'
          java-version: '25'
          java-package: 'jdk'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: maven
      - name: Fix Maven Wrapper permissions
        run: chmod +x mvnw
        if: runner.os != 'Windows'
      - name: Build
        shell: bash
        run: |
          mvn -Pnative package -Dmaven.test.skip=true
          ls target
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts ${{ matrix.version }} on ${{ matrix.os }}
          path: |
            target/hello-graalvm
            target/*.exe
